# Auto-generated by Lumenary
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Union, Literal, Annotated, Tuple, Set, Any

from datetime import datetime, date, time, timedelta
from uuid import UUID
import uuid

class TokenExchangeRequest(BaseModel):
    client_id: str
    grant_type: str
    code: Optional[str] = None
    code_verifier: Optional[str] = None

class TokenResponse(BaseModel):
    access_token: str
    token_type: str = "bearer"
    expires_in: int = 3600

class TokenValidationRequest(BaseModel):
    token: str
    
class LogoutResponse(BaseModel):
    success: bool = True

# Import user-defined models that we need for input/response models
from core.travel_user import TravelUser
from core.travel_post import TravelPost
from core.post_like import PostLike
from core.follow import Follow
from core.saved_post import SavedPost

class BodySocialServicesGetSocialFeed(BaseModel):
  user_id: UUID
  page: int
  limit: int

GetSocialFeedOutputSchema = List[Dict]
class BodySocialServicesLikePost(BaseModel):
  user_id: UUID
  post_id: UUID

LikePostOutputSchema = Dict
class BodySocialServicesSavePostToWishlist(BaseModel):
  user_id: UUID
  post_id: UUID
  collection_name: Optional[str] = None
  notes: Optional[str] = None

SavePostToWishlistOutputSchema = Dict

class BodyAIServicesGenerateTripRecommendations(BaseModel):
  user_id: UUID
  goals: List[str]
  location: Optional[str] = None
  duration: Optional[str] = None

GenerateTripRecommendationsOutputSchema = List[Dict]
class BodySocialServicesFollowUser(BaseModel):
  follower_id: UUID
  following_id: UUID

FollowUserOutputSchema = Dict
class BodySocialServicesGetUserSavedPosts(BaseModel):
  user_id: UUID
  location_filter: Optional[str] = None
  collection_filter: Optional[str] = None

GetUserSavedPostsOutputSchema = List[Dict]
class BodySocialServicesGetSavedLocations(BaseModel):
  user_id: UUID

GetSavedLocationsOutputSchema = List[Dict]
class BodySocialServicesCreateTravelPost(BaseModel):
  user_id: UUID
  caption: str
  images: List[str]
  location_name: str
  country: str
  post_type: str
  category: str
  tags: List[str]
  city: Optional[str] = None
  booking_info: Optional[Dict] = None

CreateTravelPostOutputSchema = TravelPost
    

# ==================== REVIEWS SCHEMAS ====================

from core.review import Review
from core.review_vote import ReviewVote

class BodySocialServicesCreateReview(BaseModel):
  user_id: UUID
  post_id: UUID
  rating: int = Field(..., ge=1, le=5, description="Rating from 1 to 5 stars")
  comment: Optional[str] = None

CreateReviewOutputSchema = Dict

class BodySocialServicesGetPostReviews(BaseModel):
  post_id: UUID
  page: int = 0
  limit: int = 20

GetPostReviewsOutputSchema = Dict

class BodySocialServicesUpdateReview(BaseModel):
  user_id: UUID
  review_id: UUID
  rating: Optional[int] = Field(None, ge=1, le=5, description="Rating from 1 to 5 stars")
  comment: Optional[str] = None

UpdateReviewOutputSchema = Dict

class BodySocialServicesDeleteReview(BaseModel):
  user_id: UUID
  review_id: UUID

DeleteReviewOutputSchema = Dict

class BodySocialServicesVoteReview(BaseModel):
  user_id: UUID
  review_id: UUID
  is_helpful: bool = Field(..., description="True if helpful, False if not helpful")

VoteReviewOutputSchema = Dict
