// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { SocialServicesGetSocialFeedData, SocialServicesGetSocialFeedResponse, SocialServicesGetSocialFeedError, SocialServicesLikePostData, SocialServicesLikePostResponse, SocialServicesLikePostError, SocialServicesSavePostToWishlistData, SocialServicesSavePostToWishlistResponse, SocialServicesSavePostToWishlistError, SocialServicesFollowUserData, SocialServicesFollowUserResponse, SocialServicesFollowUserError, SocialServicesGetUserSavedPostsData, SocialServicesGetUserSavedPostsResponse, SocialServicesGetUserSavedPostsError, SocialServicesGetSavedLocationsData, SocialServicesGetSavedLocationsResponse, SocialServicesGetSavedLocationsError, SocialServicesCreateTravelPostData, SocialServicesCreateTravelPostResponse, SocialServicesCreateTravelPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Social Services Get Social Feed
 * Get Instagram-style social feed for a user based on who they follow.
 */
export const socialServicesGetSocialFeed = <ThrowOnError extends boolean = false>(options: Options<SocialServicesGetSocialFeedData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesGetSocialFeedResponse, SocialServicesGetSocialFeedError, ThrowOnError>({
        url: '/api/social_services/get_social_feed',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Like Post
 * Like or unlike a post.
 */
export const socialServicesLikePost = <ThrowOnError extends boolean = false>(options: Options<SocialServicesLikePostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesLikePostResponse, SocialServicesLikePostError, ThrowOnError>({
        url: '/api/social_services/like_post',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Save Post To Wishlist
 * Save a post to user&#39;s wishlist.
 */
export const socialServicesSavePostToWishlist = <ThrowOnError extends boolean = false>(options: Options<SocialServicesSavePostToWishlistData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesSavePostToWishlistResponse, SocialServicesSavePostToWishlistError, ThrowOnError>({
        url: '/api/social_services/save_post_to_wishlist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Follow User
 * Follow or unfollow a user.
 */
export const socialServicesFollowUser = <ThrowOnError extends boolean = false>(options: Options<SocialServicesFollowUserData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesFollowUserResponse, SocialServicesFollowUserError, ThrowOnError>({
        url: '/api/social_services/follow_user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Get User Saved Posts
 * Get user&#39;s saved posts organized by location/collection.
 */
export const socialServicesGetUserSavedPosts = <ThrowOnError extends boolean = false>(options: Options<SocialServicesGetUserSavedPostsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesGetUserSavedPostsResponse, SocialServicesGetUserSavedPostsError, ThrowOnError>({
        url: '/api/social_services/get_user_saved_posts',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Get Saved Locations
 * Get unique locations from user&#39;s saved posts for organization.
 */
export const socialServicesGetSavedLocations = <ThrowOnError extends boolean = false>(options: Options<SocialServicesGetSavedLocationsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesGetSavedLocationsResponse, SocialServicesGetSavedLocationsError, ThrowOnError>({
        url: '/api/social_services/get_saved_locations',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Social Services Create Travel Post
 * Create a new travel post.
 */
export const socialServicesCreateTravelPost = <ThrowOnError extends boolean = false>(options: Options<SocialServicesCreateTravelPostData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<SocialServicesCreateTravelPostResponse, SocialServicesCreateTravelPostError, ThrowOnError>({
        url: '/api/social_services/create_travel_post',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};