// This file is auto-generated by @hey-api/openapi-ts

export type BodySocialServicesCreateTravelPost = {
    user_id: string;
    caption: string;
    images: Array<string>;
    location_name: string;
    country: string;
    post_type: string;
    category: string;
    tags: Array<string>;
    city?: string | null;
    booking_info?: {
        [key: string]: unknown;
    } | null;
};

export type BodySocialServicesFollowUser = {
    follower_id: string;
    following_id: string;
};

export type BodySocialServicesGetSavedLocations = {
    user_id: string;
};

export type BodySocialServicesGetSocialFeed = {
    user_id: string;
    page: number;
    limit: number;
};

export type BodySocialServicesGetUserSavedPosts = {
    user_id: string;
    location_filter?: string | null;
    collection_filter?: string | null;
};

export type BodySocialServicesLikePost = {
    user_id: string;
    post_id: string;
};

export type BodySocialServicesSavePostToWishlist = {
    user_id: string;
    post_id: string;
    collection_name?: string | null;
    notes?: string | null;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type TravelPost = {
    id?: string;
    user_id: string;
    caption: string;
    images: Array<string>;
    location_name: string;
    location_coordinates?: {
        [key: string]: unknown;
    } | null;
    country: string;
    city?: string | null;
    post_type: string;
    category: string;
    tags: Array<string>;
    likes_count?: number;
    saves_count?: number;
    comments_count?: number;
    shares_count?: number;
    booking_info?: {
        [key: string]: unknown;
    } | null;
    experience_rating?: number | null;
    price_range?: string | null;
    created_at?: string;
    updated_at?: string;
    is_published?: boolean;
    is_featured?: boolean;
    is_sponsored?: boolean;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type SocialServicesGetSocialFeedData = {
    body: BodySocialServicesGetSocialFeed;
    path?: never;
    query?: never;
    url: '/api/social_services/get_social_feed';
};

export type SocialServicesGetSocialFeedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesGetSocialFeedError = SocialServicesGetSocialFeedErrors[keyof SocialServicesGetSocialFeedErrors];

export type SocialServicesGetSocialFeedResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SocialServicesGetSocialFeedResponse = SocialServicesGetSocialFeedResponses[keyof SocialServicesGetSocialFeedResponses];

export type SocialServicesLikePostData = {
    body: BodySocialServicesLikePost;
    path?: never;
    query?: never;
    url: '/api/social_services/like_post';
};

export type SocialServicesLikePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesLikePostError = SocialServicesLikePostErrors[keyof SocialServicesLikePostErrors];

export type SocialServicesLikePostResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SocialServicesLikePostResponse = SocialServicesLikePostResponses[keyof SocialServicesLikePostResponses];

export type SocialServicesSavePostToWishlistData = {
    body: BodySocialServicesSavePostToWishlist;
    path?: never;
    query?: never;
    url: '/api/social_services/save_post_to_wishlist';
};

export type SocialServicesSavePostToWishlistErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesSavePostToWishlistError = SocialServicesSavePostToWishlistErrors[keyof SocialServicesSavePostToWishlistErrors];

export type SocialServicesSavePostToWishlistResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SocialServicesSavePostToWishlistResponse = SocialServicesSavePostToWishlistResponses[keyof SocialServicesSavePostToWishlistResponses];

export type SocialServicesFollowUserData = {
    body: BodySocialServicesFollowUser;
    path?: never;
    query?: never;
    url: '/api/social_services/follow_user';
};

export type SocialServicesFollowUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesFollowUserError = SocialServicesFollowUserErrors[keyof SocialServicesFollowUserErrors];

export type SocialServicesFollowUserResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type SocialServicesFollowUserResponse = SocialServicesFollowUserResponses[keyof SocialServicesFollowUserResponses];

export type SocialServicesGetUserSavedPostsData = {
    body: BodySocialServicesGetUserSavedPosts;
    path?: never;
    query?: never;
    url: '/api/social_services/get_user_saved_posts';
};

export type SocialServicesGetUserSavedPostsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesGetUserSavedPostsError = SocialServicesGetUserSavedPostsErrors[keyof SocialServicesGetUserSavedPostsErrors];

export type SocialServicesGetUserSavedPostsResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SocialServicesGetUserSavedPostsResponse = SocialServicesGetUserSavedPostsResponses[keyof SocialServicesGetUserSavedPostsResponses];

export type SocialServicesGetSavedLocationsData = {
    body: BodySocialServicesGetSavedLocations;
    path?: never;
    query?: never;
    url: '/api/social_services/get_saved_locations';
};

export type SocialServicesGetSavedLocationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesGetSavedLocationsError = SocialServicesGetSavedLocationsErrors[keyof SocialServicesGetSavedLocationsErrors];

export type SocialServicesGetSavedLocationsResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type SocialServicesGetSavedLocationsResponse = SocialServicesGetSavedLocationsResponses[keyof SocialServicesGetSavedLocationsResponses];

export type SocialServicesCreateTravelPostData = {
    body: BodySocialServicesCreateTravelPost;
    path?: never;
    query?: never;
    url: '/api/social_services/create_travel_post';
};

export type SocialServicesCreateTravelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SocialServicesCreateTravelPostError = SocialServicesCreateTravelPostErrors[keyof SocialServicesCreateTravelPostErrors];

export type SocialServicesCreateTravelPostResponses = {
    /**
     * Successful Response
     */
    200: TravelPost;
};

export type SocialServicesCreateTravelPostResponse = SocialServicesCreateTravelPostResponses[keyof SocialServicesCreateTravelPostResponses];